spring.application.name=UniReserveBackend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/unireserve
spring.datasource.username=postgres
spring.datasource.password=curry13118915
spring.jpa.hibernate.ddl-auto=validate
jwt.secret=/+OA3FC0TTYwlk1MywQ0iQtBOyFqNdnsGOs92VP+MgrXpA7QJrGDxGL1Cnf/MPAhc+OhnjCds8HBJ7Yn2U29HQ==
jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:5173
spring.security.oauth2.client.registration.google.client-id=949029861322-legn3adc25jrv8dik2ue64g2lr9qb7r4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG